basePath: /api/v1
definitions:
  handler.heroResponse:
    properties:
      actual_name:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Kyrex
    url: github.com/kyrex23
  description: API about the Marvel Cinematic Universe (MCU)
  title: Marvel API
  version: 1.0.0
paths:
  /heroes:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: List of heroes retrieved successfully
          schema:
            items:
              $ref: '#/definitions/handler.heroResponse'
            type: array
      summary: Get the list of heroes
      tags:
      - Heroes
  /heroes/{id}:
    get:
      parameters:
      - description: Hero ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Hero found successfully
          schema:
            $ref: '#/definitions/handler.heroResponse'
        "404":
          description: Hero not found
      summary: Get a hero by ID
      tags:
      - Heroes
swagger: "2.0"
